include Makefile

CC      = gcc
CFLAGS  = -pipe -O0 -g3 -Wall -Wextra -Werror -pedantic -Wshadow
LDFLAGS = -pipe

PATH_BUILD = build
PATH_SRC   = src
PATH_TEST  = test

GITHASH = $(shell git rev-parse --short HEAD)

SRC_GPERF = \
	src/handlers/irc_ctcp.gperf.out \
	src/handlers/irc_recv.gperf.out \
	src/handlers/irc_send.gperf.out \

gperf: $(SRC_GPERF)

%.gperf.out: %.gperf
	gperf --output-file=$@ $<

OBJ_D := $(patsubst $(PATH_SRC)/%.c, $(PATH_BUILD)/%.o, $(SRC))
OBJ_T := $(patsubst $(PATH_SRC)/%.c, $(PATH_BUILD)/%.t, $(SRC))
OBJ_T += $(PATH_BUILD)/utils/tree.t

$(PATH_BUILD)/%.o: $(PATH_SRC)/%.c | config.h $(PATH_BUILD) $(MBEDTLS)
	@echo "$(CC) $(CFLAGS) $<"
	@$(CPP) $(CFLAGS) $(MBEDTLS_CFLAGS) -std=c11 -I. -D_POSIX_C_SOURCE=200809L -DVERSION=$(VERSION) -DGITHASH=$(GITHASH) -MM -MP -MT $@ -MF $(@:.o=.o.d) $<
	@$(CC)  $(CFLAGS) $(MBEDTLS_CFLAGS) -std=c11 -I. -D_POSIX_C_SOURCE=200809L -DVERSION=$(VERSION) -DGITHASH=$(GITHASH) -c -o $@ $<

$(PATH_BUILD)/%.t: $(PATH_TEST)/%.c | config.h $(PATH_BUILD) $(MBEDTLS)
	@$(CPP) $(CFLAGS) $(MBEDTLS_CFLAGS) -std=c11 -I. -D_POSIX_C_SOURCE=200809L -DVERSION=$(VERSION) -DGITHASH=$(GITHASH) -MM -MP -MT $@ -MF $(@:.t=.t.d) $<
	@$(CC)  $(CFLAGS) $(MBEDTLS_CFLAGS) -std=c11 -I. -D_POSIX_C_SOURCE=200809L -DVERSION=$(VERSION) -DGITHASH=$(GITHASH) -c -o $(@:.t=.t.o) $<
	@$(CC)  $(LDFLAGS) -o $@ $(@:.t=.t.o) $(MBEDTLS)
	@{ rm -f $(@:.t=.td) && ./$@; } || mv $@ $(@:.t=.td)

rirc.debug: config.h $(OBJ_D) $(MBEDTLS)
	@echo "$(CC) $(LDFLAGS) $@"
	@$(CC) $(LDFLAGS) -pthread $(OBJ_D) $(MBEDTLS) -o $@

check: $(OBJ_T)
	@[ ! "$$(find $(PATH_BUILD) -name '*.td' -print -quit)" ] && echo OK

$(PATH_BUILD):
	@mkdir -p $(patsubst src%, build%, $(shell find src -type d))

clean-dev: clean
	@rm -rfv rirc.debug $(PATH_BUILD)

clean-lib:
	@rm -rf $(MBEDTLS_SRC)

-include $(OBJ_D:.o=.o.d)
-include $(OBJ_T:.t=.t.d)
