'\" t
.TH RIRC 1 rirc\-VERSION
.SH NAME
rirc \- a minimalistic irc client written in C
.SH SYNOPSIS
.B rirc
.RB [ -hv ]
.RB [ -s
.I server
.RB [ -p
.IR port ]
.RB [ -w
.IR pass ]
.RB [ -n
.IR nicks ]
.RB [ -c
.IR chans "]
.RB [ -u
.IR username "]
.RB [ -r
.IR realname "]], ...]"
.SH DESCRIPTION
.P
rirc is a lightweight Internet Relay Chat client.
.P
Customization of rirc can be accomplished by editing the
.I config.h
file and (re)compiling the source code.
.SH OPTIONS
.TP
.B -h, --help
Print this message and exit
.TP
.B -v, --version
Print rirc version and exit
.TP
.BI "-s, --server=" server
Connect to
.I server
.TP
.BI "-p, --port=" port
Connect to
.I server
using
.I port
.TP
.BI "-w, --pass=" pass
Connect to
.I server
using
.I pass
.TP
.BI "-u, --username=" username
Connect to
.I server
using
.I username
.TP
.BI "-r, --realname=" realname
Connect to
.I server
using
.I realname
.TP
.BI "-n, --nicks=" nicks
Comma separated list of
.I nicks
to use for
.I server
.TP
.BI "-c, --chans=" chans
Comma separated list of
.I chans
to join on
.I server
.SH USAGE
.TS
l .
rirc can be controlled by a combination of key bindings and commands, where:
  <arg> denotes required arguments
  [arg] denotes optional arguments
.TE

.TS
.tab(;);
lb l .
Commands:
  /close
  /connect;[host:port | host [port]]
  /disconnect;[quit message]
  /ignore [nick]
  /join;[target, [targets...]]
  /me;<message>
  /nick;[nick]
  /part;[target [targets...]] [part message]
  /priv;<target> <message>
  /quit;[quit message]
  /raw;<message>
  /unignore;[nick]
  /version
.TE

.TS
.tab(;);
lb l .
Keys:
  ^F;find channel
  ^N;go to next channel
  ^P;go to previous channel
  ^C;cancel current input/action
  ^L;clear current channel
  ^X;close current channel
  ^U;scroll current buffer up
  ^D;scroll current buffer down
.TE

.SH AUTHORS
.MT mail@rcr.io
Richard 'rcr' Robbins
.ME
.SH LICENSE
See the
.I LICENSE
file in the source directory for the terms of redistribution.
.SH SEE ALSO
See
.UR http://rcr.io/rirc/
.UE
for additional documentation.
.SH BUGS
See the
.I TODO
file in the source directory for current known issues.
