package(default_visibility = ["//visibility:public"])

cc_library(
    name = "components",
    srcs = glob([
        "*.c",
        "*.h",
    ]),
    deps = [
        "//:config",
        "//src:state_h",
        "//src/utils",
    ],
)
