#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>

#include "draw.h"
#include "state.h"
#include "utils.h"

/* Fail macros used in message sending/receiving handlers */
#define fail(M) \
	do { if (err) { strncpy(err, M, MAX_ERROR); } return 1; } while (0)

/* Fail with formatted message */
#define failf(...) \
	do { if (err) { snprintf(err, MAX_ERROR, __VA_ARGS__); } return 1; } while (0)

/* Conditionally fail */
#define fail_if(C) \
	do { if (C) return 1; } while (0)

#define IS_ME(X) !strcmp(X, s->nick)

/* Must be kept in sync with mesg.gperf hash table */
#define SEND_HANDLERS \
	X(clear) \
	X(close) \
	X(connect) \
	X(ctcp) \
	X(disconnect) \
	X(ignore) \
	X(join) \
	X(me) \
	X(msg) \
	X(nick) \
	X(part) \
	X(privmsg) \
	X(quit) \
	X(raw) \
	X(topic) \
	X(unignore) \
	X(version)

/* Send handler prototypes */
#define X(cmd) static int send_##cmd(char*, char*, struct server*, struct channel*);
SEND_HANDLERS
#undef X

/* Must be kept in sync with mesg.gperf hash table */
#define RECV_HANDLERS \
	X(error) \
	X(join) \
	X(kick) \
	X(mode) \
	X(nick) \
	X(notice) \
	X(part) \
	X(ping) \
	X(pong) \
	X(privmsg) \
	X(quit) \
	X(topic)

/* Recv handler prototypes */
#define X(cmd) static int recv_##cmd(char*, struct parsed_mesg*, struct server*);
RECV_HANDLERS
#undef X

/* Special cases handlers, CTCP messages are embedded in PRIVMSG */
static int recv_ctcp_req(char*, struct parsed_mesg*, struct server*);
static int recv_ctcp_rpl(char*, struct parsed_mesg*, struct server*);

/* Special case handler for numeric replies */
static int recv_numeric(char*, struct parsed_mesg*, struct server*);

/* Handler for errors deemed fatal to a server's state */
static void server_fatal(struct server*, char*, ...);

/* Numeric Reply Codes */
enum numeric {
	RPL_WELCOME          =   1,
	RPL_YOURHOST         =   2,
	RPL_CREATED          =   3,
	RPL_MYINFO           =   4,
	RPL_ISUPPORT         =   5,
	RPL_STATSCONN        = 250,
	RPL_LUSERCLIENT      = 251,
	RPL_LUSEROP          = 252,
	RPL_LUSERUNKNOWN     = 253,
	RPL_LUSERCHANNELS    = 254,
	RPL_LUSERME          = 255,
	RPL_LOCALUSERS       = 265,
	RPL_GLOBALUSERS      = 266,
	RPL_CHANNEL_URL      = 328,
	RPL_NOTOPIC          = 331,
	RPL_TOPIC            = 332,
	RPL_TOPICWHOTIME     = 333,
	RPL_NAMREPLY         = 353,
	RPL_ENDOFNAMES       = 366,
	RPL_MOTD             = 372,
	RPL_MOTDSTART        = 375,
	RPL_ENDOFMOTD        = 376,
	ERR_NOSUCHNICK       = 401,
	ERR_NOSUCHSERVER     = 402,
	ERR_NOSUCHCHANNEL    = 403,
	ERR_CANNOTSENDTOCHAN = 404,
	ERR_ERRONEUSNICKNAME = 432,
	ERR_NICKNAMEINUSE    = 433,
	ERR_INVITEONLYCHAN   = 473,
	ERR_NOCHANMODES      = 477
};

static void
server_fatal(struct server *s, char *fmt, ...)
{
	/* Encountered an error fatal to a server, disconnect and begin a reconnect */
	char errbuff[MAX_ERROR];
	va_list ap;

	va_start(ap, fmt);
	vsnprintf(errbuff, MAX_ERROR, fmt, ap);
	va_end(ap);

	server_disconnect(s, 1, 0, errbuff);
}

/*
 * Message sending handlers
 * */

struct send_handler
{
	char *name;
	int (*func)(char*, char*, struct server*, struct channel*);
};

static unsigned int
send_handler_hash(register const char *str, register size_t len)
{
	/* Perfect hash function, generated by gperf mesg.gperf */

	static const unsigned char asso_values[] = {
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25,  5,  5,  5,
		25, 10, 25,  0, 20, 25, 25,  0,  0,  0,
		 0, 15,  0,  5,  0,  0, 10,  0, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25
	};

	register unsigned int hval = len;

	switch (hval) {
		default:
			hval += asso_values[(unsigned char)str[2]];
		/* FALLTHROUGH */
		case 2:
		case 1:
			hval += asso_values[(unsigned char)str[0]];
			break;
    }

	return hval;
}

const struct send_handler*
send_handler_lookup(register const char *str, register size_t len)
{
	/* Perfect hash function lookup, generated by gperf mesg.gperf */

	enum {
		TOTAL_KEYWORDS  = 17,
		MIN_WORD_LENGTH = 2,
		MAX_WORD_LENGTH = 10,
		MIN_HASH_VALUE  = 2,
		MAX_HASH_VALUE  = 24
	};

	static const struct send_handler send_handlers[] = {
		{"",           NULL},
		{"",           NULL},
		{"ME",         send_me},
		{"RAW",        send_raw},
		{"PART",       send_part},
		{"TOPIC",      send_topic},
		{"IGNORE",     send_ignore},
		{"PRIVMSG",    send_privmsg},
		{"UNIGNORE",   send_unignore},
		{"NICK",       send_nick},
		{"CLOSE",      send_close},
		{"",           NULL},
		{"CONNECT",    send_connect},
		{"MSG",        send_msg},
		{"CTCP",       send_ctcp},
		{"CLEAR",      send_clear},
		{"",           NULL},
		{"VERSION",    send_version},
		{"",           NULL},
		{"QUIT",       send_quit},
		{"DISCONNECT", send_disconnect},
		{"",           NULL},
		{"",           NULL},
		{"",           NULL},
		{"JOIN",       send_join}
    };

	if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH) {

		register unsigned int key = send_handler_hash(str, len);

		if (key <= MAX_HASH_VALUE) {

			register const char *s = send_handlers[key].name;

			if (*str == *s && !strcmp(str + 1, s + 1))
				return &send_handlers[key];
		}
	}

	return NULL;
}

void
send_mesg(char *mesg, struct channel *chan)
{
	/* Handle the input to a channel, ie:
	 *	- a default message to the channel
	 *	- a default message to the channel beginning with '/'
	 *	- a handled command beginning with '/'
	 *	- an unhandled command beginning with '/'
	 */

	char *p, *cmd_str, errbuff[MAX_ERROR];

	if (*mesg == '/' && *(++mesg) != '/') {

		int err;

		if (!(cmd_str = getarg(&mesg, " "))) {
			newline(chan, 0, "-!!-", "Messages beginning with '/' require a command");
			return;
		}

		/* command -> COMMAND */
		for (p = cmd_str; *p; p++)
			*p = toupper(*p);

		const struct send_handler* handler = send_handler_lookup(cmd_str, strlen(cmd_str));

		if (handler)
			err = handler->func(errbuff, mesg, chan->server, chan);
		else
			err = sendf(errbuff, chan->server, "%s %s", cmd_str, mesg);

		if (err)
			newline(chan, 0, "-!!-", errbuff);

	} else {

		/* Send to current channel */

		if (*mesg == 0)
			fatal("message is empty", 0);

		else if (chan->buffer.type != BUFFER_CHANNEL && chan->buffer.type != BUFFER_PRIVATE)
			newline(chan, 0, "-!!-", "Error: This is not a channel");

		else if (chan->parted)
			newline(chan, 0, "-!!-", "Error: Parted from channel");

		else if (sendf(errbuff, chan->server, "PRIVMSG %s :%s", chan->name.str, mesg))
			newline(chan, 0, "-!!-", errbuff);

		else
			newline(chan, BUFFER_LINE_CHAT, chan->server->nick, mesg);
	}
}

static int
send_clear(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /clear [channel] */

	char *targ;
	struct channel *cc;

	if (!(targ = getarg(&mesg, " ")))
		channel_clear(c);
	else if ((cc = channel_list_get(&s->clist, targ)))
		channel_clear(cc);
	else
		failf("Error: Channel '%s' not found", targ);

	return 0;
}

static int
send_close(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /close [channel] */

	char *targ;
	struct channel *cc;

	if (!(targ = getarg(&mesg, " ")))
		channel_close(c);
	else if ((cc = channel_list_get(&s->clist, targ)))
		channel_close(cc);
	else
		failf("Error: Channel '%s' not found", targ);

	return 0;
}

static int
send_connect(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /connect [(host) | (host:port) | (host port)] */

	UNUSED(c);

	char *host, *port;

	if (!(host = getarg(&mesg, " :"))) {

		/* If no hostname arg is given, attempt to reconnect on the current server */

		if (!s)
			fail("Error: /connect <host | host:port | host port>");

		else if (s->soc >= 0 || s->connecting)
			fail("Error: Already connected or reconnecting to server");

		host = s->host;
		port = s->port;

	} else if (!(port = getarg(&mesg, " "))) {
		port = "6667";
	}

	server_connect(host, port, NULL, NULL);

	return 0;
}

static int
send_ctcp(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /ctcp <target> <message> */

	UNUSED(c);

	char *targ, *p;

	if (!(targ = getarg(&mesg, " ")))
		fail("Error: /ctcp <target> <command> [arguments]");

	/* Crude to check that at least some ctcp command exists */
	while (*mesg == ' ')
		mesg++;

	if (*mesg == '\0')
		fail("Error: /ctcp <target> <command> [arguments]");

	/* Ensure the command is uppercase */
	for (p = mesg; *p && *p != ' '; p++)
		*p = toupper(*p);

	return sendf(err, s, "PRIVMSG %s :\x01""%s\x01", targ, mesg);
}

static int
send_disconnect(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /disconnect [quit message] */

	UNUSED(c);

	/* Server isn't connecting, connected or waiting to connect */
	if (!s || (!s->connecting && s->soc < 0 && !s->reconnect_time))
		fail("Error: Not connected to server");

	server_disconnect(s, 0, 0, (*mesg) ? mesg : DEFAULT_QUIT_MESG);

	return 0;
}

static int
send_me(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /me <message> */

	if (c->buffer.type == BUFFER_SERVER)
		fail("Error: This is not a channel");

	if (c->parted)
		fail("Error: Parted from channel");

	fail_if(sendf(err, s, "PRIVMSG %s :\x01""ACTION %s\x01", c->name.str, mesg));

	newlinef(c, 0, "*", "%s %s", s->nick, mesg);

	return 0;
}

static int
send_ignore(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /ignore [nick] */

	char *nick;

	if (!s)
		fail("Error: Not connected to server");

	if (!(nick = getarg(&mesg, " ")))
		user_list_print(c);

	else if (!user_list_add(&(s->ignore), nick, 0))
		failf("Error: Already ignoring '%s'", nick);

	else
		newlinef(c, 0, "--", "Ignoring '%s'", nick);

	return 0;
}

static int
send_join(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /join [target[,targets]*] */

	char *targ;

	if ((targ = getarg(&mesg, " ")))
		return sendf(err, s, "JOIN %s", targ);

	if (c->buffer.type == BUFFER_SERVER)
		fail("Error: JOIN requires a target");

	if (c->buffer.type == BUFFER_PRIVATE)
		fail("Error: Can't rejoin private buffers");

	if (!c->parted)
		fail("Error: Not parted from channel");

	return sendf(err, s, "JOIN %s", c->name.str);
}

static int
send_msg(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* Alias for /priv */

	return send_privmsg(err, mesg, s, c);
}

static int
send_nick(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /nick [nick] */

	char *nick;

	if ((nick = getarg(&mesg, " ")))
		return sendf(err, s, "NICK %s", nick);

	if (!s)
		fail("Error: Not connected to server");

	newlinef(c, 0, "--", "Your nick is %s", s->nick);

	return 0;
}

static int
send_part(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /part [[target[,targets]*] part message]*/

	char *targ;

	if ((targ = getarg(&mesg, " ")))
		return sendf(err, s, "PART %s :%s", targ, (*mesg) ? mesg : DEFAULT_QUIT_MESG);

	if (c->buffer.type == BUFFER_SERVER)
		fail("Error: PART requires a target");

	if (c->buffer.type == BUFFER_PRIVATE)
		fail("Error: Can't part private buffers");

	if (c->parted)
		fail("Error: Already parted from channel");

	return sendf(err, s, "PART %s :%s", c->name.str, DEFAULT_QUIT_MESG);
}

static int
send_privmsg(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /(priv | msg) <target> <message> */

	char *targ;
	struct channel *cc;

	if (!(targ = getarg(&mesg, " ")))
		fail("Error: Private messages require a target");

	if (*mesg == '\0')
		fail("Error: Private messages was null");

	fail_if(sendf(err, s, "PRIVMSG %s :%s", targ, mesg));

	if ((cc = channel_list_get(&s->clist, targ)) == NULL)
		cc = new_channel(targ, s, c, BUFFER_PRIVATE);

	newline(cc, BUFFER_LINE_CHAT, s->nick, mesg);

	return 0;
}

static int
send_raw(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /raw <raw message> */

	fail_if(sendf(err, s, "%s", mesg));

	newline(c, 0, "RAW >>", mesg);

	return 0;
}

static int
send_topic(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /topic [topic] */

	/* If no actual message is given, retrieve the current topic */
	while (*mesg == ' ')
		mesg++;

	if (*mesg == '\0')
		return sendf(err, s, "TOPIC %s", c->name.str);

	return sendf(err, s, "TOPIC %s :%s", c->name.str, mesg);
}

static int
send_unignore(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /unignore [nick] */

	char *nick;

	if (!s)
		fail("Error: Not connected to server");

	if (!(nick = getarg(&mesg, " ")))
		user_list_print(c);

	else if (!user_list_del(&(s->ignore), nick))
		failf("Error: '%s' not on ignore list", nick);

	else
		newlinef(c, 0, "--", "No longer ignoring '%s'", nick);

	return 0;
}

static int
send_quit(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /quit [quit message] */

	UNUSED(c);
	UNUSED(err);

	struct server *t;

	if (s) do {
		t = s;
		s = s->next;
		server_disconnect(t, 0, 1, (*mesg) ? mesg : DEFAULT_QUIT_MESG);
	} while (t != s);

	exit(EXIT_SUCCESS);

	return 0;
}

static int
send_version(char *err, char *mesg, struct server *s, struct channel *c)
{
	/* /version [target] */

	char *targ;

	if (s == NULL) {
		newline(c, 0, "--", "rirc v"VERSION);
		newline(c, 0, "--", "http://rcr.io/rirc");
		return 0;
	}

	if ((targ = getarg(&mesg, " ")))
		return sendf(err, s, "VERSION %s", targ);
	else
		return sendf(err, s, "VERSION");
}

/*
 * Message receiving handlers
 * */

struct recv_handler
{
	char *name;
	int (*func)(char*, struct parsed_mesg*, struct server*);
};

static unsigned int
recv_handler_hash(register const char *str, register size_t len)
{
	static const unsigned char asso_values[] = {
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 14, 25, 25, 25,  5,
		25, 25, 25,  5,  9, 15, 25,  4,  5,  0,
		 0, 10,  0, 25,  0,  5, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
		25, 25, 25, 25, 25, 25
    };

	return len + asso_values[(unsigned char)str[1]] + asso_values[(unsigned char)str[0]];
}

const struct recv_handler *
recv_handler_lookup (register const char *str, register size_t len)
{
	enum {
		TOTAL_KEYWORDS  = 12,
		MIN_WORD_LENGTH = 4,
		MAX_WORD_LENGTH = 7,
		MIN_HASH_VALUE  = 4,
		MAX_HASH_VALUE  = 24
	};

	static const struct recv_handler recv_handlers[] = {
		{"",        NULL},
		{"",        NULL},
		{"",        NULL},
		{"",        NULL},
		{"PONG",    recv_pong},
		{"TOPIC",   recv_topic},
		{"",        NULL},
		{"PRIVMSG", recv_privmsg},
		{"MODE",    recv_mode},
		{"PING",    recv_ping},
		{"ERROR",   recv_error},
		{"NOTICE",  recv_notice},
		{"",        NULL},
		{"JOIN",    recv_join},
		{"NICK",    recv_nick},
		{"",        NULL},
		{"",        NULL},
		{"",        NULL},
		{"PART",    recv_part},
		{"QUIT",    recv_quit},
		{"",        NULL},
		{"",        NULL},
		{"",        NULL},
		{"",        NULL},
		{"KICK",    recv_kick}
	};

	if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH) {

		register unsigned int key = recv_handler_hash (str, len);

		if (key <= MAX_HASH_VALUE) {
			register const char *s = recv_handlers[key].name;

			if (*str == *s && !strcmp (str + 1, s + 1))
				return &recv_handlers[key];
		}
	}

	return 0;
}

void
recv_mesg(char *inp, int count, struct server *s)
{
	/* FIXME Move to connection struct, handle in net. recv_mesg should
	 * only receive messages ready to parse */
	char *ptr = s->iptr;
	char *max = s->input + BUFFSIZE;

	char errbuff[MAX_ERROR];

	while (count--) {
		if (*inp == '\r') {

			int err = 0;

			*ptr = '\0';

#ifdef DEBUG
			newline(s->channel, 0, "DEBUG <<", s->input);
#endif
			const struct recv_handler* handler;

			struct parsed_mesg p;

			if (!(parse_mesg(&p, s->input)))
				newlinef(s->channel, 0, "-!!-", "Failed to parse: %s", s->input);

			else if (isdigit(*p.command))
				err = recv_numeric(errbuff, &p, s);

			else if ((handler = recv_handler_lookup(p.command, strlen(p.command))))
				err = handler->func(errbuff, &p, s);

			else
				newlinef(s->channel, 0, "-!!-", "Message type '%s' unknown", p.command);

			if (err)
				newline(s->channel, 0, "-!!-", errbuff);

			ptr = s->input;

		/* Don't accept unprintable characters unless space or ctcp markup */
		} else if (ptr < max && (isgraph(*inp) || *inp == ' ' || *inp == 0x01))
			*ptr++ = *inp;

		inp++;
	}

	s->iptr = ptr;
}

static int
recv_ctcp_req(char *err, struct parsed_mesg *p, struct server *s)
{
	/* CTCP Requests:
	 * PRIVMSG <target> :0x01<command> <arguments>0x01
	 *
	 * All replies must be:
	 * NOTICE <target> :0x01<reply>0x01 */

	char *targ, *cmd, *mesg;

	if (!p->from)
		fail("CTCP: sender's nick is null");

	/* CTCP request from ignored user, do nothing */
	if (user_list_get(&(s->ignore), p->from, 0))
		return 0;

	if (!(targ = getarg(&p->params, " ")))
		fail("CTCP: target is null");

	if (!(mesg = getarg(&p->trailing, "\x01")))
		fail("CTCP: invalid markup");

	/* Markup is valid, get command */
	if (!(cmd = getarg(&mesg, " ")))
		fail("CTCP: command is null");

	/* Handle the CTCP request if supported */

	if (!strcmp(cmd, "ACTION")) {
		/* ACTION <message> */

		struct channel *c;

		if (IS_ME(targ)) {
			/* Sending emote to private channel */

			if ((c = channel_list_get(&s->clist, p->from)) == NULL)
				c = new_channel(p->from, s, s->channel, BUFFER_PRIVATE);

			if (c != ccur) {
				c->activity = ACTIVITY_PINGED;
				draw_nav();
			}

		} else if ((c = channel_list_get(&s->clist, targ)) == NULL)
			failf("CTCP ACTION: channel '%s' not found", targ);

		newlinef(c, 0, "*", "%s %s", p->from, mesg);

		return 0;
	}

	if (!strcmp(cmd, "CLIENTINFO")) {
		/* CLIENTINFO
		 *
		 * Returns a list of CTCP commands supported by rirc */

		newlinef(s->channel, 0, "--", "CTCP CLIENTINFO request from %s", p->from);

		return sendf(err, s, "NOTICE %s :\x01""CLIENTINFO ACTION PING VERSION TIME\x01", p->from);
	}

	if (!strcmp(cmd, "PING")) {
		/* PING
		 *
		 * Returns a millisecond precision timestamp */

		struct timeval t;

		gettimeofday(&t, NULL);

		long long milliseconds = t.tv_sec * 1000LL + t.tv_usec;

		newlinef(s->channel, 0, "--", "CTCP PING request from %s", p->from);

		return sendf(err, s, "NOTICE %s :\x01""PING %lld\x01", p->from, milliseconds);
	}

	if (!strcmp(cmd, "VERSION")) {
		/* VERSION
		 *
		 * Returns version info about rirc */

		newlinef(s->channel, 0, "--", "CTCP VERSION request from %s", p->from);

		return sendf(err, s,
			"NOTICE %s :\x01""VERSION rirc v"VERSION", http://rcr.io/rirc\x01", p->from);
	}

	if (!strcmp(cmd, "TIME")) {
		/* TIME
		 *
		 * Returns the localtime in human readable form */

		char time_str[64];
		struct tm *tm;
		time_t t;

		t = time(NULL);
		tm = localtime(&t);

		/* Mon Jan 01 20:30 GMT */
		strftime(time_str, sizeof(time_str), "%a %b %d %H:%M %Z", tm);

		newlinef(s->channel, 0, "--", "CTCP TIME request from %s", p->from);

		return sendf(err, s, "NOTICE %s :\x01""TIME %s\x01", p->from, time_str);
	}

	/* Unsupported CTCP request */
	fail_if(sendf(err, s, "NOTICE %s :\x01""ERRMSG %s not supported\x01", p->from, cmd));
	failf("CTCP: Unknown command '%s' from %s", cmd, p->from);
}

static int
recv_ctcp_rpl(char *err, struct parsed_mesg *p, struct server *s)
{
	/* CTCP replies:
	 * NOTICE <target> :0x01<command> <arguments>0x01 */

	char *cmd, *mesg;

	if (!p->from)
		fail("CTCP: sender's nick is null");

	/* CTCP reply from ignored user, do nothing */
	if (user_list_get(&(s->ignore), p->from, 0))
		return 0;

	if (!(mesg = getarg(&p->trailing, "\x01")))
		fail("CTCP: invalid markup");

	/* Markup is valid, get command */
	if (!(cmd = getarg(&mesg, " ")))
		fail("CTCP: command is null");

	newlinef(s->channel, 0, p->from, "CTCP %s reply: %s", cmd, mesg);

	return 0;
}

static int
recv_error(char *err, struct parsed_mesg *p, struct server *s)
{
	/* ERROR :<message> */

	UNUSED(err);

	server_disconnect(s, 1, 0, p->trailing ? p->trailing : "Remote hangup");

	return 0;
}

static int
recv_join(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick!user@hostname.domain JOIN [:]<channel> */

	//FIXME: chan / targ
	char *chan;
	struct channel *c;

	if (!p->from)
		fail("JOIN: sender's nick is null");

	if (!(chan = getarg(&p->params, " ")) && !(chan = getarg(&p->trailing, " ")))
		fail("JOIN: channel is null");

	if (IS_ME(p->from)) {
		if ((c = channel_list_get(&s->clist, chan)) == NULL)
			channel_set_current(new_channel(chan, s, ccur, BUFFER_CHANNEL));
		else {
			c->parted = 0;
			newlinef(c, 0, ">", "You have rejoined %s", chan);
		}
		draw_all();
	} else {

		if ((c = channel_list_get(&s->clist, chan)) == NULL)
			failf("JOIN: channel '%s' not found", chan);

		user_list_add(&(c->users), p->from, 0);

		if (c->users.count < config.join_part_quit_threshold)
			newlinef(c, 0, ">", "%s!%s has joined %s", p->from, p->host, chan);

		draw_status();
	}

	return 0;
}

static int
recv_kick(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick!user@hostname.domain KICK <channel> <user> :comment */

	char *chan, *user;
	struct channel *c;

	if (!p->from)
		fail("KICK: sender's nick is null");

	if (!(chan = getarg(&p->params, " ")))
		fail("KICK: channel is null");

	if (!(user = getarg(&p->params, " ")))
		fail("KICK: user is null");

	if ((c = channel_list_get(&s->clist, chan)) == NULL)
		failf("KICK: channel '%s' not found", chan);

	/* RFC 2812, section 3.2.8:
	 *
	 * If a "comment" is given, this will be sent instead of the default message,
	 * the nickname of the user issuing the KICK.
	 * */
	if (!strcmp(p->from, p->trailing))
		p->trailing = NULL;

	if (IS_ME(user)) {

		part_channel(c);

		if (p->trailing)
			newlinef(c, 0, "--", "You've been kicked by %s (%s)", p->from, p->trailing);
		else
			newlinef(c, 0, "--", "You've been kicked by %s", p->from, user);
	} else {

		if (!user_list_del(&(c->users), user))
			failf("KICK: nick '%s' not found in '%s'", user, chan);

		if (p->trailing)
			newlinef(c, 0, "--", "%s has kicked %s (%s)", p->from, user, p->trailing);
		else
			newlinef(c, 0, "--", "%s has kicked %s", p->from, user);
	}

	draw_status();

	return 0;
}

static int
recv_mode(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick!user@hostname.domain MODE <targ> *( ( "-" / "+" ) *<modes> *<modeparams> ) */

	/* TODO:
	 *
	 * Breaking recv_mode, needs full rewrite.
	 *
	 * Get target as either:
	 *   - usermode (rirc user)
	 *   - chanmode (channel)
	 *   - prfxmode (user on channel (flag in PREFIX))
	 *
	 * Call the appropriate mode setting function
	 *
	 * Draw the appropriate component
	 *
	 * */

	/* FIXME
	 * MODE user :+abc
	 * MODE #chan +abc
	 */

	UNUSED(err);
	UNUSED(p);
	UNUSED(s);

	return 0;
}

static int
recv_nick(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick!user@hostname.domain NICK [:]<new nick> */

	char *nick;

	if (!p->from)
		fail("NICK: old nick is null");

	/* Some servers seem to send the new nick in the trailing */
	if (!(nick = getarg(&p->params, " ")) && !(nick = getarg(&p->trailing, " ")))
		fail("NICK: new nick is null");

	if (IS_ME(p->from)) {
		strncpy(s->nick, nick, NICKSIZE);
		newlinef(s->channel, 0, "--", "You are now known as %s", nick);
	}

	struct channel *c = s->channel;
	//TODO: channel_list_foreach
	do {
		if (user_list_rpl(&(c->users), p->from, nick))
			newlinef(c, 0, "--", "%s  >>  %s", p->from, nick);
	} while ((c = c->next) != s->channel);

	return 0;
}

static int
recv_notice(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick.hostname.domain NOTICE <target> :<message> */

	char *targ;
	struct channel *c;

	if (!p->trailing)
		fail("NOTICE: message is null");

	/* CTCP reply */
	if (*p->trailing == 0x01)
		return recv_ctcp_rpl(err, p, s);

	if (!p->from)
		fail("NOTICE: sender's nick is null");

	/* Notice from ignored user, do nothing */
	if (user_list_get(&(s->ignore), p->from, 0))
		return 0;

	if (!(targ = getarg(&p->params, " ")))
		fail("NOTICE: target is null");

	if ((c = channel_list_get(&s->clist, targ)))
		newline(c, 0, p->from, p->trailing);
	else
		newline(s->channel, 0, p->from, p->trailing);

	return 0;
}

static int
recv_numeric(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :server <code> <target> [args] */

	char *targ, *nick, *chan, *time, *type, *num;
	int ret, _code;

	struct channel *c;

	/* Extract numeric code */
	for (_code = 0; isdigit(*p->command); p->command++) {

		_code = _code * 10 + (*p->command - '0');

		if (_code > 999)
			fail("NUMERIC: greater than 999");
	}

	enum numeric code = _code;

	/* Message target is only used to establish s->nick when registering with a server */
	if (!(targ = getarg(&p->params, " "))) {
		server_fatal(s, "NUMERIC: target is null");
		return 1;
	}

	/* Message target should match s->nick or '*' if unregistered, otherwise out of sync */
	if (strcmp(targ, s->nick) && strcmp(targ, "*") && code != RPL_WELCOME) {
		server_fatal(s, "NUMERIC: target mismatched, nick is '%s', received '%s'", s->nick, targ);
		return 1;
	}

	switch (code) {

	/* 001 :<Welcome message> */
	case RPL_WELCOME:
		/* Establishing new connection with a server, set initial nick,
		 * handle any channel auto-join or rejoins */

		strncpy(s->nick, targ, NICKSIZE);

		/* Reset list of auto nicks */
		s->nptr = s->nicks;

		/* Auto join channels if first time connecting */
		if (s->join) {
			ret = sendf(err, s, "JOIN %s", s->join);
			free(s->join);
			s->join = NULL;
			fail_if(ret);
		} else {
			/* If reconnecting to server, join any non-parted channels */
			c = s->channel;
			//TODO: channel_list_foreach
			do {
				if (c->buffer.type == BUFFER_CHANNEL && !c->parted)
					fail_if(sendf(err, s, "JOIN %s", c->name.str));
				c = c->next;
			} while (c != s->channel);
		}

		if (p->trailing)
			newline(s->channel, 0, "--", p->trailing);

		newlinef(s->channel, 0, "--", "You are known as %s", s->nick);
		break;


	case RPL_YOURHOST:  /* 002 :<Host info, server version, etc> */
	case RPL_CREATED:   /* 003 :<Server creation date message> */

		/* FIXME: trailing can be null, here and elsewhere, eg `:d 003 nick VG` */
		newline(s->channel, 0, "--", p->trailing);
		break;


	case RPL_MYINFO:    /* 004 <params> :Are supported by this server */

		newlinef(s->channel, 0, "--", "%s ~ supported by this server", p->params);

		server_set_004(s, p->params);
		break;

	case RPL_ISUPPORT:  /* 005 <params> :Are supported by this server */

		newlinef(s->channel, 0, "--", "%s ~ supported by this server", p->params);

		server_set_005(s, p->params);
		break;


	/* 328 <channel> :<url> */
	case RPL_CHANNEL_URL:

		if (!(chan = getarg(&p->params, " ")))
			fail("RPL_CHANNEL_URL: channel is null");

		if ((c = channel_list_get(&s->clist, chan)) == NULL)
			failf("RPL_CHANNEL_URL: channel '%s' not found", chan);

		newlinef(c, 0, "--", "URL for %s is: \"%s\"", chan, p->trailing);
		break;


	/* 332 <channel> :<topic> */
	case RPL_TOPIC:

		if (!(chan = getarg(&p->params, " ")))
			fail("RPL_TOPIC: channel is null");

		if ((c = channel_list_get(&s->clist, chan)) == NULL)
			failf("RPL_TOPIC: channel '%s' not found", chan);

		newlinef(c, 0, "--", "Topic for %s is \"%s\"", chan, p->trailing);
		break;


	/* 333 <channel> <nick> <time> */
	case RPL_TOPICWHOTIME:

		if (!(chan = getarg(&p->params, " ")))
			fail("RPL_TOPICWHOTIME: channel is null");

		if (!(nick = getarg(&p->params, " ")))
			fail("RPL_TOPICWHOTIME: nick is null");

		if (!(time = getarg(&p->params, " ")))
			fail("RPL_TOPICWHOTIME: time is null");

		if ((c = channel_list_get(&s->clist, chan)) == NULL)
			failf("RPL_TOPICWHOTIME: channel '%s' not found", chan);

		time_t raw_time = atoi(time);
		time = ctime(&raw_time);

		newlinef(c, 0, "--", "Topic set by %s, %s", nick, time);
		break;


	/* 353 ("="/"*"/"@") <channel> :*([ "@" / "+" ]<nick>) */
	case RPL_NAMREPLY:
		/* @:secret   *:private   =:public */
		if (!(type = getarg(&p->params, " ")))
			fail("RPL_NAMEREPLY: type is null");

		if (!(chan = getarg(&p->params, " ")))
			fail("RPL_NAMEREPLY: channel is null");

		if ((c = channel_list_get(&s->clist, chan)) == NULL)
			failf("RPL_NAMEREPLY: channel '%s' not found", chan);

		if ((ret = mode_chanmode_prefix(&(c->chanmodes), &(s->mode_config), *type))) {
			; //TODO: report mode error message as non-fatal warning
		}

		while ((nick = getarg(&p->trailing, " "))) {

			char prefix = 0;

			/* TODO: mode_usermode_prefix, report error messages as non-fatal warnings */
			if (!irc_isnickchar(*nick))
				prefix = *nick++;

			user_list_add(&(c->users), nick, prefix);
		}

		draw_status();
		break;


	case RPL_STATSCONN:    /* 250 :<Message> */
	case RPL_LUSERCLIENT:  /* 251 :<Message> */

		newline(s->channel, 0, "--", p->trailing);
		break;


	case RPL_LUSEROP:        /* 252 <int> :IRC Operators online */
	case RPL_LUSERUNKNOWN:   /* 253 <int> :Unknown connections */
	case RPL_LUSERCHANNELS:  /* 254 <int> :Channels formed */

		if (!(num = getarg(&p->params, " ")))
			num = "NULL";

		newlinef(s->channel, 0, "--", "%s %s", num, p->trailing);
		break;


	case RPL_LUSERME:      /* 255 :I have <int> clients and <int> servers */
	case RPL_LOCALUSERS:   /* 265 <int> <int> :Local users <int>, max <int> */
	case RPL_GLOBALUSERS:  /* 266 <int> <int> :Global users <int>, max <int> */
	case RPL_MOTD:         /* 372 :- <text> */
	case RPL_MOTDSTART:    /* 375 :- <server> Message of the day - */

		newline(s->channel, 0, "--", p->trailing);
		break;


	/* Not printing these */
	case RPL_NOTOPIC:     /* 331 <chan> :<Message> */
	case RPL_ENDOFNAMES:  /* 366 <chan> :<Message> */
	case RPL_ENDOFMOTD:   /* 376 :End of MOTD command */
		break;


	case ERR_NOSUCHNICK:    /* <nick> :<reason> */
	case ERR_NOSUCHSERVER:  /* <server> :<reason> */
	case ERR_NOSUCHCHANNEL: /* <channel> :<reason> */

		if (!(targ = getarg(&p->params, " "))) {
			if (code == ERR_NOSUCHNICK)
				fail("ERR_NOSUCHNICK: nick is null");
			if (code == ERR_NOSUCHSERVER)
				fail("ERR_NOSUCHSERVER: server is null");
			if (code == ERR_NOSUCHCHANNEL)
				fail("ERR_NOSUCHCHANNEL: channel is null");
		}

		/* Private buffer might not exist */
		if ((c = channel_list_get(&s->clist, targ)) == NULL)
			c = s->channel;

		if (p->trailing)
			newlinef(c, 0, "--", "Cannot send to '%s': %s", targ, p->trailing);
		else
			newlinef(c, 0, "--", "Cannot send to '%s'", targ);
		break;


	case ERR_CANNOTSENDTOCHAN:  /* <channel> :<reason> */

		if (!(chan = getarg(&p->params, " ")))
			fail("ERR_CANNOTSENDTOCHAN: channel is null");

		/* Channel buffer might not exist */
		if ((c = channel_list_get(&s->clist, chan)) == NULL)
			c = s->channel;

		if (p->trailing)
			newlinef(c, 0, "--", "Cannot send to '%s': %s", chan, p->trailing);
		else
			newlinef(c, 0, "--", "Cannot send to '%s'", chan);
		break;


	case ERR_ERRONEUSNICKNAME:  /* 432 <nick> :<reason> */

		if (!(nick = getarg(&p->params, " ")))
			fail("ERR_ERRONEUSNICKNAME: nick is null");

		newlinef(s->channel, 0, "-!!-", "'%s' - %s", nick, p->trailing);
		break;


	case ERR_NICKNAMEINUSE:  /* 433 <nick> :Nickname is already in use */

		if (!(nick = getarg(&p->params, " ")))
			fail("ERR_NICKNAMEINUSE: nick is null");

		newlinef(s->channel, 0, "-!!-", "Nick '%s' in use", nick);

		if (IS_ME(nick)) {
			auto_nick(&(s->nptr), s->nick);

			newlinef(s->channel, 0, "-!!-", "Trying again with '%s'", s->nick);

			return sendf(err, s, "NICK %s", s->nick);
		}
		break;


	case ERR_INVITEONLYCHAN:
	case ERR_NOCHANMODES:

		if (p->trailing)
			newlinef(s->channel, 0, "--", "%s: %s", p->params, p->trailing);
		else
			newlinef(s->channel, 0, "--", "%s", p->params);
		break;


	default:

		newlinef(s->channel, 0, "UNHANDLED", "%d %s :%s", code, p->params, p->trailing);
		break;
	}

	return 0;
}

static int
recv_part(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick!user@hostname.domain PART <channel> [:message] */

	char *targ;
	struct channel *c;

	if (!p->from)
		fail("PART: sender's nick is null");

	if (!(targ = getarg(&p->params, " ")))
		fail("PART: target is null");

	if (IS_ME(p->from)) {

		/* If receving a PART message from myself channel isn't found, assume it was closed */
		if ((c = channel_list_get(&s->clist, targ)) != NULL) {

			part_channel(c);

			if (p->trailing)
				newlinef(c, 0, "<", "you have left %s (%s)", targ, p->trailing);
			else
				newlinef(c, 0, "<", "you have left %s", targ);
		}

		draw_status();

		return 0;
	}

	if ((c = channel_list_get(&s->clist, targ)) == NULL)
		failf("PART: channel '%s' not found", targ);

	if (!user_list_del(&(c->users), p->from))
		failf("PART: nick '%s' not found in '%s'", p->from, targ);

	if (c->users.count < config.join_part_quit_threshold) {
		if (p->trailing)
			newlinef(c, 0, "<", "%s!%s has left %s (%s)", p->from, p->host, targ, p->trailing);
		else
			newlinef(c, 0, "<", "%s!%s has left %s", p->from, p->host, targ);
	}

	draw_status();

	return 0;
}

static int
recv_ping(char *err, struct parsed_mesg *p, struct server *s)
{
	/* PING :<server> */

	if (!p->trailing)
		fail("PING: server is null");

	return sendf(err, s, "PONG %s", p->trailing);
}

static int
recv_pong(char *err, struct parsed_mesg *p, struct server *s)
{
	/*  PONG <server> [<server2>] */

	UNUSED(err);

	/*  PING sent explicitly by the user */
	if (!s->pinging)
		newlinef(s->channel, 0, "!!", "PONG %s", p->params);

	s->pinging = 0;

	return 0;
}

static int
recv_privmsg(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick!user@hostname.domain PRIVMSG <target> :<message> */

	char *targ;
	struct channel *c;

	if (!p->trailing)
		fail("PRIVMSG: message is null");

	/* CTCP request */
	if (*p->trailing == 0x01)
		return recv_ctcp_req(err, p, s);

	if (!p->from)
		fail("PRIVMSG: sender's nick is null");

	/* Privmsg from ignored user, do nothing */
	if (user_list_get(&(s->ignore), p->from, 0))
		return 0;

	if (!(targ = getarg(&p->params, " ")))
		fail("PRIVMSG: target is null");

	/* Find the target channel */
	if (IS_ME(targ)) {

		if ((c = channel_list_get(&s->clist, p->from)) == NULL)
			c = new_channel(p->from, s, s->channel, BUFFER_PRIVATE);

		if (c != ccur) {
			c->activity = ACTIVITY_PINGED;
			draw_nav();
		}

	} else if ((c = channel_list_get(&s->clist, targ)) == NULL)
		failf("PRIVMSG: channel '%s' not found", targ);

	if (check_pinged(p->trailing, s->nick)) {

		bell();

		if (c != ccur) {
			c->activity = ACTIVITY_PINGED;
			draw_nav();
		}

		newline(c, BUFFER_LINE_PINGED, p->from, p->trailing);
	} else
		newline(c, BUFFER_LINE_CHAT, p->from, p->trailing);

	return 0;
}

static int
recv_quit(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick!user@hostname.domain QUIT [:message] */

	if (!p->from)
		fail("QUIT: sender's nick is null");

	struct channel *c = s->channel;
	//TODO: channel_list_foreach
	do {
		if (user_list_del(&(c->users), p->from)) {
			if (c->users.count < config.join_part_quit_threshold) {
				if (p->trailing)
					newlinef(c, 0, "<", "%s!%s has quit (%s)", p->from, p->host, p->trailing);
				else
					newlinef(c, 0, "<", "%s!%s has quit", p->from, p->host);
			}
		}
		c = c->next;
	} while (c != s->channel);

	draw_status();

	return 0;
}

static int
recv_topic(char *err, struct parsed_mesg *p, struct server *s)
{
	/* :nick!user@hostname.domain TOPIC <channel> :[topic] */

	char *targ;
	struct channel *c;

	if (!p->from)
		fail("TOPIC: sender's nick is null");

	if (!(targ = getarg(&p->params, " ")))
		fail("TOPIC: target is null");

	if (!p->trailing)
		fail("TOPIC: topic is null");

	if ((c = channel_list_get(&s->clist, targ)) == NULL)
		failf("TOPIC: channel '%s' not found", targ);

	if (*p->trailing) {
		newlinef(c, 0, "--", "%s has changed the topic:", p->from);
		newlinef(c, 0, "--", "\"%s\"", p->trailing);
	} else {
		newlinef(c, 0, "--", "%s has unset the topic", p->from);
	}

	return 0;
}
